import main
main.main()

In [1]:
import pickle
import modules
year = 2022
with open(rf"../output/pickles/{year}.pickle", 'rb') as inputdata:
            db = pickle.load(inputdata)

with open(rf"../output/pickles/{year-1}.pickle", 'rb') as inputdata:
            df = pickle.load(inputdata)

In [38]:
keepers = [
        pd.read_csv(f"../Data/FBREF_{year-1}"+"-"+f"{year-2000}"+"/" + f)
        for f in [f"keeper_{year-2000}.csv", f"keeper_adv_{year-2000}.csv"]
    ]

In [51]:
# Get Players names for this dataset (FPL)
# Get Stats (Historic will be tricky)
#

,first_name,second_name,goals_scored,assists,total_points,minutes,goals_conceded,creativity,influence,threat,bonus,bps,ict_index,clean_sheets,red_cards,yellow_cards,selected_by_percent,now_cost,element_type
0,Bernd,Leno,0,0,10,360,9,0.0,85.0,0.0,0,69,8.5,1,0,0,0.8,45,GK
1,Rúnar Alex,Rúnarsson,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.5,40,GK
2,Willian,Borges Da Silva,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.1,63,MID
3,Pierre-Emerick,Aubameyang,4,1,44,1036,16,132.4,217.6,582.0,7,131,92.9,6,0,3,1.2,96,FWD
4,Cédric,Soares,1,1,48,1481,27,306.5,246.0,76.0,3,292,63.0,3,0,3,0.4,42,DEF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
732,Bruno André,Cavaco Jordão,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,45,MID
733,Toti António,Gomes,0,0,6,360,6,4.3,59.6,28.0,0,52,9.2,0,0,1,0.0,44,DEF
734,Dion,Sanderson,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,40,DEF
735,Ryan,Giles,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,45,MID
736,Francisco Jorge,Tomás Oliveira,0,3,20,203,5,83.4,99.4,118.0,2,67,30.1,0,0,0,0.0,55,MID

In [60]:
player_name = "mohamed salah"
tables = pd.read_html(modules.constants.FBREF_SEARCH_URL + player_name.replace(" ", "+"))
table_num = len(tables)
scout_num = int((table_num - 9) / 2)
table_names = []
for i in range(scout_num):
    table_names.append(f"scout_{i}")
    table_names.append(f"similar_{i}")
    table_names.sort()

table_names += modules.constants.FBREF_PLAYER_LABELS

ValueError: No tables found

In [59]:
tables

[                 Statistic Per 90  Percentile
 0        Non-Penalty Goals   0.38        76.0
 1           Non-Penalty xG   0.19        27.0
 2              Shots Total   2.32        54.0
 3                  Assists   0.06         3.0
 4                      xAG   0.17        26.0
 5               npxG + xAG   0.37        27.0
 6    Shot-Creating Actions   3.66        38.0
 7                      NaN    NaN         NaN
 8         Passes Attempted  27.79         8.0
 9        Pass Completion %  78.5%        61.0
 10      Progressive Passes   2.44        34.0
 11      Dribbles Completed   2.25        87.0
 12       Touches (Att Pen)   4.82        71.0
 13  Progressive Passes Rec   6.16        67.0
 14                     NaN    NaN         NaN
 15                 Tackles   1.56        74.0
 16           Interceptions   0.31        24.0
 17                  Blocks   0.94        63.0
 18              Clearances   0.25        24.0
 19             Aerials won   0.28        26.0,
                  Statistic Per 90  Percentile
 0        Non-Penalty Goals   0.38        53.0
 1           Non-Penalty xG   0.19         6.0
 2              Shots Total   2.32        37.0
 3                  Assists   0.06        26.0
 4                      xAG   0.17        75.0
 5               npxG + xAG   0.37        17.0
 6    Shot-Creating Actions   3.66        88.0
 7                      NaN    NaN         NaN
 8         Passes Attempted  27.79        79.0
 9        Pass Completion %  78.5%        91.0
 10      Progressive Passes   2.44        90.0
 11      Dribbles Completed   2.25        97.0
 12       Touches (Att Pen)   4.82        53.0
 13  Progressive Passes Rec   6.16        58.0
 14                     NaN    NaN         NaN
 15                 Tackles   1.56        97.0
 16           Interceptions   0.31        81.0
 17                  Blocks   0.94        81.0
 18              Clearances   0.25        14.0
 19             Aerials won   0.28         4.0,
    Rk             Player   Nation                    Squad  Compare
 0   1   Gianluca Caprari   it ITA                    Monza  Compare
 1   2     Jonathan Ikone   fr FRA               Fiorentina  Compare
 2   3    Mattia Zaccagni   it ITA                    Lazio  Compare
 3   4      Saïd Benrahma   dz ALG          West Ham United  Compare
 4   5     Miguel Almirón   py PAR         Newcastle United  Compare
 5   6     Daniel Podence   pt POR  Wolverhampton Wanderers  Compare
 6   7  Philippe Coutinho   br BRA              Aston Villa  Compare
 7   8  Giacomo Raspadori   it ITA                   Napoli  Compare
 8   9      Nikola Vlašić   hr CRO                   Torino  Compare
 9  10    Raheem Sterling  eng ENG                  Chelsea  Compare,
    Rk            Player  Nation                Squad  Compare
 0   1      Amine Gouiri  fr FRA               Rennes  Compare
 1   2     Kévin Gameiro  fr FRA           Strasbourg  Compare
 2   3      Rafael Borré  co COL  Eintracht Frankfurt  Compare
 3   4    Alexis Sánchez  cl CHI            Marseille  Compare
 4   5   Roberto Firmino  br BRA            Liverpool  Compare
 5   6           Rodrigo  es ESP         Leeds United  Compare
 6   7  Georginio Rutter  fr FRA         Leeds United  Compare
 7   8        Iago Aspas  es ESP           Celta Vigo  Compare
 8   9    Jonathan David  ca CAN                Lille  Compare
 9  10      Bryan Mbeumo  cm CMR            Brentford  Compare,
              Unnamed: 0_level_0           Unnamed: 1_level_0  \
                          Season                          Age
 0                     2009-2010                           16
 1                     2010-2011                           17
 2                     2011-2012                           18
 3                     2012-2013                           19
 4                     2013-2014                           20
 5                     2013-2014                           20
 6                     2014-2015                           21
 7                     2015-2016                           22
 8                     2016-2017                           23
 9                     2017-2018                           24
 10                    2018-2019                           25
 11                    2019-2020                           26
 12                    2020-2021                           27
 13                    2021-2022                           28
 14                    2022-2023                           29
 15                   14 Seasons                   14 Seasons
 16                          NaN                          NaN
 17  Crystal Palace (13 Seasons)  Crystal Palace (13 Seasons)
 18      Cardiff City (1 Season)      Cardiff City (1 Season)
 19    Manchester Utd (1 Season)    Manchester Utd (1 Season)
 20                          NaN                          NaN
 21  Premier League (10 Seasons)  Premier League (10 Seasons)
 22     Championship (4 Seasons)     Championship (4 Seasons)

              Unnamed: 2_level_0 Unnamed: 3_level_0 Unnamed: 4_level_0  \
                           Squad            Country               Comp
 0                Crystal Palace            eng ENG    2. Championship
 1                Crystal Palace            eng ENG    2. Championship
 2                Crystal Palace            eng ENG    2. Championship
 3                Crystal Palace            eng ENG    2. Championship
 4                  Cardiff City            eng ENG  1. Premier League
 5                Manchester Utd            eng ENG  1. Premier League
 6                Crystal Palace            eng ENG  1. Premier League
 7                Crystal Palace            eng ENG  1. Premier League
 8                Crystal Palace            eng ENG  1. Premier League
 9                Crystal Palace            eng ENG  1. Premier League
 10               Crystal Palace            eng ENG  1. Premier League
 11               Crystal Palace            eng ENG  1. Premier League
 12               Crystal Palace            eng ENG  1. Premier League
 13               Crystal Palace            eng ENG  1. Premier League
 14               Crystal Palace            eng ENG  1. Premier League
 15                      3 Clubs                NaN          2 Leagues
 16                          NaN            Country               Comp
 17  Crystal Palace (13 Seasons)                NaN          2 Leagues
 18      Cardiff City (1 Season)                NaN           1 League
 19    Manchester Utd (1 Season)                NaN           1 League
 20                          NaN                NaN                NaN
 21  Premier League (10 Seasons)                NaN                NaN
 22     Championship (4 Seasons)                NaN                NaN

    Unnamed: 5_level_0 Playing Time                        ... Expected        \
                LgRank           MP  Starts    Min    90s  ...       xG  npxG
 0                21st            1       0     11    0.1  ...      NaN   NaN
 1                20th           41      26   2632   29.2  ...      NaN   NaN
 2                17th           41      34   3156   35.1  ...      NaN   NaN
 3                 5th           43      43   3809   42.3  ...      NaN   NaN
 4                20th           12       5    586    6.5  ...      NaN   NaN
 5                 7th            2       0     30    0.3  ...      NaN   NaN
 6                10th           31      23   1977   22.0  ...      NaN   NaN
 7                15th           34      30   2488   27.6  ...      NaN   NaN
 8                14th           35      34   3019   33.5  ...      NaN   NaN
 9                11th           29      28   2549   28.3  ...      9.2   9.2
 10               12th           34      34   3036   33.7  ...      5.7   5.7
 11               14th           38      37   3280   36.4  ...      5.2   5.2
 12               14th           30      29   2612   29.0  ...      8.1   6.5
 13               12th           33      31   2760   30.7  ...     11.0   5.4
 14               12th           17      17   1507   16.7  ...      5.0   3.3
 15                NaN          421     371  33452  371.7  ...     44.2  35.3
 16             LgRank           MP  Starts    Min    90s  ...       xG  npxG
 17                NaN          407     366  32836  364.8  ...     44.2  35.3
 18                NaN           12       5    586    6.5  ...      NaN   NaN
 19                NaN            2       0     30    0.3  ...      NaN   NaN
 20                NaN          NaN     NaN    NaN    NaN  ...      NaN   NaN
 21                NaN          295     268  23844  264.9  ...     44.2  35.3
 22                NaN          126     103   9608  106.8  ...      NaN   NaN

                    Per 90 Minutes                                \
      xAG  npxG+xAG             xG   xAG  xG+xAG  npxG  npxG+xAG
 0    NaN       NaN            NaN   NaN     NaN   NaN       NaN
 1    NaN       NaN            NaN   NaN     NaN   NaN       NaN
 2    NaN       NaN            NaN   NaN     NaN   NaN       NaN
 3    NaN       NaN            NaN   NaN     NaN   NaN       NaN
 4    NaN       NaN            NaN   NaN     NaN   NaN       NaN
 5    NaN       NaN            NaN   NaN     NaN   NaN       NaN
 6    NaN       NaN            NaN   NaN     NaN   NaN       NaN
 7    NaN       NaN            NaN   NaN     NaN   NaN       NaN
 8    NaN       NaN            NaN   NaN     NaN   NaN       NaN
 9    4.7      13.9           0.33  0.17    0.49  0.33      0.49
 10   4.8      10.6           0.17  0.14    0.31  0.17      0.31
 11   4.0       9.1           0.14  0.11    0.25  0.14      0.25
 12   3.1       9.6           0.28  0.11    0.39  0.22      0.33
 13   6.8      12.2           0.36  0.22    0.58  0.17      0.40
 14   2.3       5.6           0.30  0.13    0.44  0.20      0.33
 15  25.7      61.0           0.25  0.15    0.40  0.20      0.35
 16   xAG  npxG+xAG             xG   xAG  xG+xAG  npxG  npxG+xAG
 17  25.7      61.0           0.25  0.15    0.40  0.20      0.35
 18   NaN       NaN            NaN   NaN     NaN   NaN       NaN
 19   NaN       NaN            NaN   NaN     NaN   NaN       NaN
 20   NaN       NaN            NaN   NaN     NaN   NaN       NaN
 21  25.7      61.0           0.25  0.15    0.40  0.20      0.35
 22   NaN       NaN            NaN   NaN     NaN   NaN       NaN

    Unnamed: 31_level_0
                Matches
 0                  NaN
 1                  NaN
 2                  NaN
 3                  NaN
 4              Matches
 5              Matches
 6              Matches
 7              Matches
 8              Matches
 9              Matches
 10             Matches
 11             Matches
 12             Matches
 13             Matches
 14             Matches
 15                 NaN
 16             Matches
 17                 NaN
 18                 NaN
 19                 NaN
 20                 NaN
 21                 NaN
 22                 NaN

 [23 rows x 32 columns],
              Unnamed: 0_level_0           Unnamed: 1_level_0  \
                          Season                          Age
 0                     2009-2010                           16
 1                     2010-2011                           17
 2                     2011-2012                           18
 3                     2012-2013                           19
 4                     2013-2014                           20
 5                     2013-2014                           20
 6                     2014-2015                           21
 7                     2015-2016                           22
 8                     2016-2017                           23
 9                     2017-2018                           24
 10                    2018-2019                           25
 11                    2019-2020                           26
 12                    2020-2021                           27
 13                    2021-2022                           28
 14                    2022-2023                           29
 15                   14 Seasons                   14 Seasons
 16                          NaN                          NaN
 17  Crystal Palace (13 Seasons)  Crystal Palace (13 Seasons)
 18      Cardiff City (1 Season)      Cardiff City (1 Season)
 19    Manchester Utd (1 Season)    Manchester Utd (1 Season)
 20                          NaN                          NaN
 21  Premier League (10 Seasons)  Premier League (10 Seasons)
 22     Championship (4 Seasons)     Championship (4 Seasons)

              Unnamed: 2_level_0 Unnamed: 3_level_0 Unnamed: 4_level_0  \
                           Squad            Country               Comp
 0                Crystal Palace            eng ENG    2. Championship
 1                Crystal Palace            eng ENG    2. Championship
 2                Crystal Palace            eng ENG    2. Championship
 3                Crystal Palace            eng ENG    2. Championship
 4                  Cardiff City            eng ENG  1. Premier League
 5                Manchester Utd            eng ENG  1. Premier League
 6                Crystal Palace            eng ENG  1. Premier League
 7                Crystal Palace            eng ENG  1. Premier League
 8                Crystal Palace            eng ENG  1. Premier League
 9                Crystal Palace            eng ENG  1. Premier League
 10               Crystal Palace            eng ENG  1. Premier League
 11               Crystal Palace            eng ENG  1. Premier League
 12               Crystal Palace            eng ENG  1. Premier League
 13               Crystal Palace            eng ENG  1. Premier League
 14               Crystal Palace            eng ENG  1. Premier League
 15                      3 Clubs                NaN          2 Leagues
 16                          NaN            Country               Comp
 17  Crystal Palace (13 Seasons)                NaN          2 Leagues
 18      Cardiff City (1 Season)                NaN           1 League
 19    Manchester Utd (1 Season)                NaN           1 League
 20                          NaN                NaN                NaN
 21  Premier League (10 Seasons)                NaN                NaN
 22     Championship (4 Seasons)                NaN                NaN

    Unnamed: 5_level_0 Unnamed: 6_level_0 Standard            ...             \
                LgRank                90s      Gls   Sh  SoT  ...  Dist   FK
 0                21st                0.1        0  NaN    0  ...   NaN  NaN
 1                20th               29.2        1  NaN   18  ...   NaN  NaN
 2                17th               35.1        6  NaN   29  ...   NaN  NaN
 3                 5th               42.3        6  NaN   38  ...   NaN  NaN
 4                20th                6.5        0  NaN    4  ...   NaN  NaN
 5                 7th                0.3        0  NaN    0  ...   NaN  NaN
 6                10th               22.0        4  NaN   15  ...   NaN  NaN
 7                15th               27.6        2  NaN    9  ...   NaN  NaN
 8                14th               33.5        7   49   18  ...   NaN  NaN
 9                11th               28.3        9   64   26  ...  15.0    0
 10               12th               33.7       10   73   27  ...  16.7    0
 11               14th               36.4        4   61   17  ...  16.2    0
 12               14th               29.0       11   58   18  ...  16.9    0
 13               12th               30.7       14   62   26  ...  18.8    0
 14               12th               16.7        6   38   16  ...  17.4    0
 15                NaN              371.7       80  405  261  ...  16.8    0
 16             LgRank                90s      Gls   Sh  SoT  ...  Dist   FK
 17                NaN              364.8       80  405  257  ...  16.8    0
 18                NaN                6.5        0  NaN    4  ...   NaN  NaN
 19                NaN                0.3        0  NaN    0  ...   NaN  NaN
 20                NaN                NaN      NaN  NaN  NaN  ...   NaN  NaN
 21                NaN              264.9       67  405  176  ...  16.8    0
 22                NaN              106.8       13  NaN   85  ...   NaN  NaN

                Expected                               Unnamed: 24_level_0
      PK  PKatt       xG  npxG  npxG/Sh  G-xG  np:G-xG             Matches
 0     0      0      NaN   NaN      NaN   NaN      NaN                 NaN
 1     0      0      NaN   NaN      NaN   NaN      NaN                 NaN
 2     0      0      NaN   NaN      NaN   NaN      NaN                 NaN
 3     0      0      NaN   NaN      NaN   NaN      NaN                 NaN
 4     0      0      NaN   NaN      NaN   NaN      NaN             Matches
 5     0      0      NaN   NaN      NaN   NaN      NaN             Matches
 6     0      0      NaN   NaN      NaN   NaN      NaN             Matches
 7     0      0      NaN   NaN      NaN   NaN      NaN             Matches
 8     0      0      NaN   NaN      NaN   NaN      NaN             Matches
 9     0      0      9.2   9.2     0.14  -0.2     -0.2             Matches
 10    0      0      5.7   5.7     0.08  +4.3     +4.3             Matches
 11    0      0      5.2   5.2     0.08  -1.2     -1.2             Matches
 12    2      2      8.1   6.5     0.11  +2.9     +2.5             Matches
 13    5      7     11.0   5.4     0.09  +3.0     +3.6             Matches
 14    0      2      5.0   3.3     0.09  +1.0     +2.7             Matches
 15    7     11     44.2  35.3     0.10  +9.8    +11.7                 NaN
 16   PK  PKatt       xG  npxG  npxG/Sh  G-xG  np:G-xG             Matches
 17    7     11     44.2  35.3     0.10  +9.8    +11.7                 NaN
 18    0      0      NaN   NaN      NaN   NaN      NaN                 NaN
 19    0      0      NaN   NaN      NaN   NaN      NaN                 NaN
 20  NaN    NaN      NaN   NaN      NaN   NaN      NaN                 NaN
 21    7     11     44.2  35.3     0.10  +9.8    +11.7                 NaN
 22    0      0      NaN   NaN      NaN   NaN      NaN                 NaN

 [23 rows x 25 columns],
              Unnamed: 0_level_0           Unnamed: 1_level_0  \
                          Season                          Age
 0                     2009-2010                           16
 1                     2010-2011                           17
 2                     2011-2012                           18
 3                     2012-2013                           19
 4                     2013-2014                           20
 5                     2013-2014                           20
 6                     2014-2015                           21
 7                     2015-2016                           22
 8                     2016-2017                           23
 9                     2017-2018                           24
 10                    2018-2019                           25
 11                    2019-2020                           26
 12                    2020-2021                           27
 13                    2021-2022                           28
 14                    2022-2023                           29
 15                   14 Seasons                   14 Seasons
 16                          NaN                          NaN
 17  Crystal Palace (13 Seasons)  Crystal Palace (13 Seasons)
 18      Cardiff City (1 Season)      Cardiff City (1 Season)
 19    Manchester Utd (1 Season)    Manchester Utd (1 Season)
 20                          NaN                          NaN
 21  Premier League (10 Seasons)  Premier League (10 Seasons)
 22     Championship (4 Seasons)     Championship (4 Seasons)

              Unnamed: 2_level_0 Unnamed: 3_level_0 Unnamed: 4_level_0  \
                           Squad            Country               Comp
 0                Crystal Palace            eng ENG    2. Championship
 1                Crystal Palace            eng ENG    2. Championship